CREATE SCHEMA user_management;
CREATE SCHEMA testing_info;
CREATE SCHEMA infra_management;


CREATE TABLE testing_info.category (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.task (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    question TEXT NOT NULL,
    points INTEGER NOT NULL,
    correct_answer_jsonb JSONB NOT NULL,
    general_feedback TEXT,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.category_task (
    task_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    PRIMARY KEY(task_id, category_id)
);


CREATE TABLE testing_info.test (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.test_category (
    category_id INTEGER NOT NULL,
    test_id INTEGER NOT NULL,
    PRIMARY KEY(category_id, test_id)
);

CREATE TABLE testing_info.task_db_sample (
    task_id INTEGER NOT NULL,
    db_sample_id INTEGER NOT NULL,
    PRIMARY KEY(task_id, db_sample_id)
);


CREATE TABLE testing_info.xml_answer (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    feedback TEXT,
    fraction REAL NOT NULL,
    task_id INTEGER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE user_management.user_group (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE user_management.user (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.user_group_task (
    user_group_id VARCHAR(255) NOT NULL,
    task_id INTEGER NOT NULL,
    PRIMARY KEY(user_group_id, task_id)
);

CREATE TABLE user_management.user_user_group (
    user_id INTEGER NOT NULL,
    user_group_id VARCHAR(255) NOT NULL,
    PRIMARY KEY(user_id, user_group_id)
);


CREATE TABLE testing_info.db_sample (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    path TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.dbms (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.db_sample_dbms (
    db_sample_id INTEGER NOT NULL,
    dbms_id INTEGER NOT NULL,
    PRIMARY KEY(db_sample_id, dbms_id)
);

CREATE TABLE infra_management.active_db_instance (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    db_sample_id INTEGER NOT NULL,
    dbms_id INTEGER NOT NULL,
    connection_string TEXT,
    PRIMARY KEY(id)
);

ALTER TABLE testing_info.test_category
ADD FOREIGN KEY(test_id) REFERENCES testing_info.test(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.test_category
ADD FOREIGN KEY(category_id) REFERENCES testing_info.category(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.db_sample_dbms
ADD FOREIGN KEY(dbms_id) REFERENCES testing_info.dbms(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE testing_info.db_sample_dbms
ADD FOREIGN KEY(db_sample_id) REFERENCES testing_info.db_sample(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE infra_management.active_db_instance
ADD FOREIGN KEY(dbms_id) REFERENCES testing_info.dbms(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE infra_management.active_db_instance
ADD FOREIGN KEY(db_sample_id) REFERENCES testing_info.db_sample(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE testing_info.task_db_sample
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.task_db_sample
ADD FOREIGN KEY(db_sample_id) REFERENCES testing_info.db_sample(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.user_group_task
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.user_group_task
ADD FOREIGN KEY(user_group_id) REFERENCES user_management.user_group(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_management.user_user_group
ADD FOREIGN KEY(user_id) REFERENCES user_management.user(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_management.user_user_group
ADD FOREIGN KEY(user_group_id) REFERENCES user_management.user_group(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.answer
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.category_task
ADD FOREIGN KEY(category_id) REFERENCES testing_info.category(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.category_task
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;