-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA user_management;
CREATE SCHEMA testing_info;
CREATE SCHEMA infra_management;


CREATE TABLE testing_info.category (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.task (f
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    question TEXT NOT NULL,
    points INTEGER NOT NULL,
    correct_answer_jsonb JSONB,
    general_feedback TEXT,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.category_task (
    task_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    PRIMARY KEY(task_id, category_id)
);


CREATE TABLE testing_info.test (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.test_category (
    category_id INTEGER NOT NULL,
    test_id INTEGER NOT NULL,
    PRIMARY KEY(category_id, test_id)
);

CREATE TABLE testing_info.task_db_sample (
    task_id INTEGER NOT NULL,
    db_sample_id INTEGER NOT NULL,
    PRIMARY KEY(task_id, db_sample_id)
);

CREATE TABLE testing_info.answer (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    feedback TEXT,
    task_id INTEGER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE user_management.user_groups (
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(name)
);

CREATE TABLE user_management.user (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.user_groups_task (
    user_group VARCHAR(255) NOT NULL,
    task_id INTEGER NOT NULL,
    PRIMARY KEY(user_group, task_id)
);

CREATE TABLE user_management.user_user_groups (
    user_id INTEGER NOT NULL,
    user_group VARCHAR(255) NOT NULL,
    PRIMARY KEY(user_id, user_group)
);


CREATE TABLE testing_info.db_sample (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    path TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.dbms (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE testing_info.db_sample_dbms (
    db_sample_id INTEGER NOT NULL,
    dbms_id INTEGER NOT NULL,
    PRIMARY KEY(db_sample_id, dbms_id)
);

CREATE TABLE infra_management.active_db_instance (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    db_sample_id INTEGER NOT NULL,
    dbms_id INTEGER NOT NULL,
    connection_string TEXT,
    PRIMARY KEY(id)
);

ALTER TABLE testing_info.test_category
ADD CONSTRAINT test_fkey
ADD FOREIGN KEY(test_id) REFERENCES testing_info.test(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.db_sample_dbms
ADD CONSTRAINT dbms_fkey
ADD FOREIGN KEY(dbms_id) REFERENCES testing_info.dbms(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE testing_info.db_sample_dbms
ADD CONSTRAINT db_sample_fkey
ADD FOREIGN KEY(db_sample_id) REFERENCES testing_info.db_sample(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE infra_management.active_db_instance
ADD CONSTRAINT dbms_fkey
ADD FOREIGN KEY(dbms_id) REFERENCES testing_info.dbms(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE infra_management.active_db_instance
ADD CONSTRAINT db_sample_fkey
ADD FOREIGN KEY(db_sample_id) REFERENCES testing_info.db_sample(id)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE testing_info.task_db_sample
ADD CONSTRAINT task_fkey
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.task_db_sample
ADD CONSTRAINT db_sample_fkey
ADD FOREIGN KEY(db_sample_id) REFERENCES testing_info.db_sample(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.user_groups_task
ADD CONSTRAINT task_fkey
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.user_groups_task
ADD CONSTRAINT user_group_fkey
ADD FOREIGN KEY(user_group) REFERENCES user_management.user_groups(name)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_management.user_user_groups
ADD CONSTRAINT user_fkey
ADD FOREIGN KEY(user_id) REFERENCES user_management.user(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_management.user_user_groups
ADD CONSTRAINT user_group_fkey
ADD FOREIGN KEY(user_group) REFERENCES user_management.user_groups(name)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.answer
ADD CONSTRAINT task_fkey
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.test_category
ADD CONSTRAINT category_fkey
ADD FOREIGN KEY(category_id) REFERENCES testing_info.category(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.category_task
ADD CONSTRAINT category_fkey
ADD FOREIGN KEY(category_id) REFERENCES testing_info.category(id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE testing_info.category_task
ADD CONSTRAINT task_fkey
ADD FOREIGN KEY(task_id) REFERENCES testing_info.task(id)
ON UPDATE CASCADE ON DELETE CASCADE;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE testing_info.test_category DROP CONSTRAINT IF EXISTS test_fkey;
ALTER TABLE testing_info.test_category DROP CONSTRAINT IF EXISTS category_fkey;

ALTER TABLE testing_info.db_sample_dbms DROP CONSTRAINT IF EXISTS dbms_fkey;
ALTER TABLE testing_info.db_sample_dbms DROP CONSTRAINT IF EXISTS db_sample_fkey;

ALTER TABLE infra_management.active_db_instance DROP CONSTRAINT IF EXISTS dbms_fkey;
ALTER TABLE infra_management.active_db_instance DROP CONSTRAINT IF EXISTS db_sample_fkey;

ALTER TABLE testing_info.task_db_sample DROP CONSTRAINT IF EXISTS task_fkey;
ALTER TABLE testing_info.task_db_sample DROP CONSTRAINT IF EXISTS db_sample_fkey;

ALTER TABLE testing_info.user_groups_task DROP CONSTRAINT IF EXISTS task_fkey;
ALTER TABLE testing_info.user_groups_task DROP CONSTRAINT IF EXISTS user_group_fkey;

ALTER TABLE user_management.user_user_groups DROP CONSTRAINT IF EXISTS user_fkey;
ALTER TABLE user_management.user_user_groups DROP CONSTRAINT IF EXISTS user_group_fkey;

ALTER TABLE testing_info.answer DROP CONSTRAINT IF EXISTS task_fkey;

ALTER TABLE testing_info.category_task DROP CONSTRAINT IF EXISTS category_fkey;
ALTER TABLE testing_info.category_task DROP CONSTRAINT IF EXISTS task_fkey;

DROP TABLE testing_info.category_task;
DROP TABLE user_management.user_user_groups;
DROP TABLE testing_info.user_groups_task;
DROP TABLE user_management.user;
DROP TABLE user_management.user_groups;
DROP TABLE testing_info.answer;
DROP TABLE testing_info.task_db_sample;
DROP TABLE testing_info.test_category;
DROP TABLE testing_info.test;
DROP TABLE testing_info.dbms;
DROP TABLE testing_info.db_sample;
DROP TABLE testing_info.db_sample_dbms;
DROP TABLE testing_info.task;
DROP TABLE testing_info.category;
DROP TABLE infra_management.active_db_instance;

DROP SCHEMA user_management;
DROP SCHEMA testing_info;
DROP SCHEMA infra_management;
-- +goose StatementEnd